<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Testing.props" />

  <PropertyGroup>
    <Description>Consuming Kafka messages, resuming inbox messages and relaying outbox messages state machines operations.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Kafka.Operations.Inbox/Kafka.Operations.Inbox.csproj" />
    <ProjectReference Include="../Kafka.Operations.Outbox/Kafka.Operations.Outbox.csproj" />
  </ItemGroup>

</Project>
