<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Testing.props" />

  <PropertyGroup>
    <Description>Consuming. resuming, redelivering, publishing, relaying state machines.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Kafka.Operations.Inbox/Kafka.Operations.Inbox.csproj" />
    <ProjectReference Include="../Kafka.Operations.Outbox/Kafka.Operations.Outbox.csproj" />
    <ProjectReference Include="../Kafka.Operations.DeadLetter/Kafka.Operations.DeadLetter.csproj" />
  </ItemGroup>

</Project>
