set -euo pipefail
set +H

KAFKA_SERVER=${1:?missing server name}
KAFKA_NODE_ID=${2:?missing node id}
DEV_NETWORK=${3:?missing dev network}
DEV_NETWORK_DNS=${4:?missing dev network dns}
KAFKA_CLUSTER_ID=${5:?missing cluster id}

echo "starting ${KAFKA_SERVER} kafka container"
podman run \
  -e KAFKA_NODE_ID=${KAFKA_NODE_ID} \
  -e KAFKA_LISTENERS="CONTROLLER://${KAFKA_SERVER}:9093,BROKER://${KAFKA_SERVER}:9094,EXTERNAL://${KAFKA_SERVER}:9092" \
  -e KAFKA_ADVERTISED_LISTENERS="BROKER://${KAFKA_SERVER}:9094,EXTERNAL://${KAFKA_SERVER}:9092" \
  -e KAFKA_INTER_BROKER_LISTENER_NAME="BROKER" \
  -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT" \
  -e KAFKA_SASL_ENABLED_MECHANISMS="SCRAM-SHA-512" \
  -e KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS="SCRAM-SHA-512" \
  -e "KAFKA_LISTENER_NAME_EXTERNAL_SCRAM-SHA-512_SASL_JAAS_CONFIG=org.apache.kafka.common.security.scram.ScramLoginModule required;" \
  -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3 \
  -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3 \
  -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=2 \
  -e KAFKA_DEFAULT_REPLICATION_FACTOR=3 \
  -e KAFKA_MIN_INSYNC_REPLICAS=2 \
  -e KAFKA_PROCESS_ROLES="broker,controller" \
  -e KAFKA_CONTROLLER_QUORUM_VOTERS="1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093" \
  -e KAFKA_CONTROLLER_LISTENER_NAMES="CONTROLLER" \
  -e CLUSTER_ID="${KAFKA_CLUSTER_ID}" \
  --network "${DEV_NETWORK}" --hosts-file=none --dns="${DEV_NETWORK_DNS}" -d --name "${KAFKA_SERVER}" \
  docker.io/apache/kafka:4.3.1