<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Testing.props" />

  <PropertyGroup>
    <Description>Kafka observability utility functions.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Api" />
    <ProjectReference Include="../Kafka.Messages/Kafka.Messages.csproj" />
  </ItemGroup>

</Project>
