<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Testing.props" />

  <PropertyGroup>
    <Description>Kafka Instrumentation utility functions.</Description>
  </PropertyGroup>

  <ItemGroup Condition="'$(PackOnly)' != 'true'">
    <PackageReference Include="OpenTelemetry" />
  </ItemGroup>

</Project>
