<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Directory.Packing.props" />

  <PropertyGroup>
    <Description>Transactional Inbox/Outbox pattern implementation, convenient functions for Confluent Kafka. [metaproject]</Description>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeReferencedProjectInPackage</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>

  <ItemGroup>
  	<None Include="../README.md" Pack="true" PackagePath="\"/>
    <None Include="../LICENSE" Pack="true" PackagePath="\"/>

    <ProjectReference Include="../Kafka.Resiliency/Resiliency.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />

    <None Include="PublicAPI.Shipped.txt" Pack="true" PackagePath="apidocs\" />
  </ItemGroup>

  <Target Name="IncludeReferencedProjectInPackage">
    <ItemGroup>
      <!-- Include both DLL and PDB in the package output -->
      <BuildOutputInPackage Include="$(OutputPath)Clients.dll" />
      <BuildOutputInPackage Include="$(OutputPath)Clients.pdb" />
      <BuildOutputInPackage Include="$(OutputPath)StateMachines.dll" />
      <BuildOutputInPackage Include="$(OutputPath)StateMachines.pdb" />
      <BuildOutputInPackage Include="$(OutputPath)Messages.dll" />
      <BuildOutputInPackage Include="$(OutputPath)Messages.pdb" />
      <BuildOutputInPackage Include="$(OutputPath)Inbox.dll" />
      <BuildOutputInPackage Include="$(OutputPath)Inbox.pdb" />
      <BuildOutputInPackage Include="$(OutputPath)Outbox.dll" />
      <BuildOutputInPackage Include="$(OutputPath)Outbox.pdb" />
      <BuildOutputInPackage Include="$(OutputPath)Resiliency.dll" />
      <BuildOutputInPackage Include="$(OutputPath)Resiliency.pdb" />
      <BuildOutputInPackage Include="$(OutputPath)Utils.dll" />
      <BuildOutputInPackage Include="$(OutputPath)Utils.pdb" />
    </ItemGroup>
  </Target>

</Project>
